## "Pierwszy krok"
slajd 68 + weryfikacja poprawno≈õci ze slajdu 69 (Syst_rekom_2020-2021_21.11.2020.pdf)

In [1]:
import pickle
import pandas as pd
import numpy as np

In [2]:
df = pd.read_parquet('AAAAAAAAAAA.parquet')

In [2]:
df = pd.read_parquet('../../../data/partners/partner_235.parquet')

In [4]:
df['click_timestamp'] = df['click_timestamp'].dt.dayofyear

In [8]:
grouped = df.groupby('click_timestamp')

In [10]:
grouped.groups.keys()

dict_keys([274, 275, 276, 277, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307])

In [11]:
grouped.get_group(274)

,Sale,SalesAmountInEuro,time_delay_for_conversion,click_timestamp,nb_clicks_1week,product_price,product_age_group,device_type,audience_id,product_gender,...,prod_category3,prod_category4,prod_category5,prod_category6,prod_category7,product_country,product_id,product_title,partner_id,user_id
14227,0,-1.0,-1,274,-1,0.0,0,3,401,0,...,0,0,0,0,0,10,1207576,0,235,6660437
15252,0,-1.0,-1,274,-1,0.0,0,3,0,0,...,0,0,0,0,0,10,663534,0,235,5440967
15440,0,-1.0,-1,274,-1,0.0,0,3,0,0,...,0,0,0,0,0,10,891718,0,235,2947222
15778,0,-1.0,-1,274,-1,0.0,0,3,0,0,...,0,0,0,0,0,10,577791,0,235,8803914
16046,0,-1.0,-1,274,-1,0.0,0,3,0,0,...,0,0,0,0,0,10,577791,0,235,10465337
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15224885,0,-1.0,-1,274,-1,0.0,0,3,0,0,...,0,0,0,0,0,10,1520241,0,235,8716249
15225114,0,-1.0,-1,274,-1,0.0,0,7,0,0,...,0,0,0,0,0,10,1150276,0,235,4176248
15227037,0,-1.0,-1,274,-1,0.0,0,3,0,0,...,0,0,0,0,0,10,1060874,0,235,3960208
15227084,0,-1.0,-1,274,-1,0.0,0,7,14285,0,...,0,0,0,0,0,10,1140206,0,235,13263815
15228421,0,-1.0,-1,274,-1,0.0,0,3,0,0,...,0,0,0,0,0,10,1525817,0,235,3044236

In [3]:
labelEncoders = pickle.load(open("../data/lablencoder.pickle","rb"))

In [4]:
labelEncoders.get('partner_id').inverse_transform([0])

array(['017EBBBE0B84EC3065F8A4FAFA39A4B2'], dtype=object)

In [4]:
grouped = df.groupby('partner_id')

In [6]:
partners_selected_for_test_parameter_for_Mr_Riegel_20201103 =["C0F515F0A2D0A5D9F854008BA76EB537", "E3DDEB04F8AFF944B11943BB57D2F620",
"E68029E9BCE099A60571AF757CBB6A08"]
partners_selected_for_test_parameter_encoded = labelEncoders.get('partner_id').transform(partners_selected_for_test_parameter_for_Mr_Riegel_20201103)

In [7]:
partners_selected_for_test_parameter_encoded

array([235, 277, 281])

In [8]:
for partner_id, df_group_for_partner in grouped:
    if partner_id in partners_selected_for_test_parameter_encoded:
        print("test_parameter_for_Mr_Riegel_20201103 for partner_id " + str(labelEncoders.get('partner_id').inverse_transform(partner_id)) + ": ", str(df_group_for_partner.shape[0]))

test_parameter_for_Mr_Riegel_20201103 for partner_id C0F515F0A2D0A5D9F854008BA76EB537:  24079
test_parameter_for_Mr_Riegel_20201103 for partner_id E3DDEB04F8AFF944B11943BB57D2F620:  3090150
test_parameter_for_Mr_Riegel_20201103 for partner_id E68029E9BCE099A60571AF757CBB6A08:  3852

In [5]:
for v in df['partner_id'].unique():
    grouped.get_group(v).to_parquet('../../../data/partners/partner_' + str(v) + '.parquet')

In [14]:
#zapomnia≈Çem posortowaƒá po dacie
for v in range(0, 312):
    df = pd.read_parquet('../data/partners/partner_' + str(v) + '.parquet')
    df = df.sort_values(by='click_timestamp')
    df.to_parquet('../data/partners/partner_' + str(v) + '.parquet')